// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIbouI4NZJJsD2adwBSSbi9e-4u04W_Y',
    appId: '1:612274265503:android:881b7fa8a35e7799e271aa',
    messagingSenderId: '612274265503',
    projectId: 'uperks-1b5c1',
    storageBucket: 'uperks-1b5c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpy1jV384EELqdKuPfCpoB22n1dRUaiwk',
    appId: '1:612274265503:ios:7a7156350ac7051be271aa',
    messagingSenderId: '612274265503',
    projectId: 'uperks-1b5c1',
    storageBucket: 'uperks-1b5c1.firebasestorage.app',
    androidClientId: '612274265503-nuuupkikudajuun8ciecfedl0hr6fnvu.apps.googleusercontent.com',
    iosClientId: '612274265503-c4r2qmmiq7d163pihu2080bje5innemv.apps.googleusercontent.com',
    iosBundleId: 'com.example.npciHackathon',
  );

}